### ISSUE TITLE
Deprecation of old xproj / project.json format in ASP.NET Core apps

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements#1]
[Was originally on [MSDN forum](https://social.msdn.microsoft.com/Forums/azure/en-US/ae43643f-d4d6-4a5d-8c7c-4877eb72fcf0/deprecation-of-old-projectjson-format-in-aspnet-core-apps?forum=windowsazurewebsitespreview)]

### What's changing

As you are likely aware, the ASP.NET Core team has switched from the old project.json/xproj format to the new .csproj format. In Visual Studio 2017, only the new format is supported.

Accordingly, we are deprecating the old format in Azure App Service at the end of May 2017. After that, the Kudu/git engine will no longer be able to build those old projects.

### Who is affected

This change affects you if you are deploying using Kudu (git support in App Service), and your project is using project.json or .xproj files. Note that it is the act of **building** these projects on Azure that will no longer work. If you are building elsewhere, and simply deploying the build artifacts to App Service, you are not affected (but please do make sure you are not targeting a pre-release **runtime**).

### What you need to do

You need to migrate to the csproj format. See https://docs.microsoft.com/en-us/dotnet/articles/core/migration/ for detailed steps.

**Comment by cjfawcett** [comment]
Hi David

Can I just ask then if and when this will be rolled out to the Azure App Service globally? My team has a few web apps published(no git build/deploy) to App Services on the old .xproj format. Migration seemed to go smoothly, but if we had an effective from date that would be even better. 

FYI, we are deployed to mainly datacenters in Europe.

**Comment by devlead** [comment]
@cjfawcett looks like now or next couple of days
> Accordingly, we are deprecating the old format in Azure App Service at the end of May 2017.

**Comment by cjfawcett** [comment]
Thanks Mattias, I however did read this part. I am simply wondering if there is a fixed date and if it's to be introduced in a phased rollout or immediately available to all regions.

**Comment by cjfawcett** [comment]
@devlead @davidebbo I think I have quelled any further fears about this having found the following tweet https://twitter.com/davidebbo/status/867099967604670464. I had my fears about deployed apps!

**Comment by davidebbo** [comment]
@cjfawcett I updated the original text to make this clearer.

**Comment by cjfawcett** [comment]
@davidebbo Thanks David, that's much appreciated!

**Comment by guitarrapc** [comment]
Is there any way to support .csx or should all existing .csx migrate to precompile functions?
> You need to migrate to the csproj format. See https://docs.microsoft.com/en-us/dotnet/articles/core/migration/ for detailed steps.

**Comment by davidebbo** [comment]
@guitarrapc the deprecation described here only applies with Web Apps, and does not affect Function Apps in any way. You can continue to use .csx files and project.json in your Function Apps.

**Comment by guitarrapc** [comment]
@davidebbo Sound very nice. OK, I will keep .csx.

I've migrated my .csx Functions Apps to pre-compile. it brings many benefit with VS IDE, local debugging, test suitability and others. (Also met nuget restore bring volume pressure to function app 1GB limitation.)
Everything have light side and dark side, thourhg.

**Comment by Giancarlos** [comment]
Is it possible this sort of issue could be referenced in the compiler error by Azure in the future? It came as a surprise to me and wasted a few hours (this includes having to download, install and migrate the whole solution of projects). It would be nice if Azure would give more helpful compiler errors when changes like this one are made that break someone's application from building.

Thanks.

**Comment by davidebbo** [comment]
@Giancarlos we actually did just make this exact change! :) If you try deploying an xproj project now, you should see something like this in the build output:

```
remote: Building Asp.Net Core .xproj is no longer supported in Azure, please move to .csproj
remote: For more information, please visit https://go.microsoft.com/fwlink/?linkid=850964
remote: Error - Changes committed to remote repository but deployment to website failed.
```

**Comment by Giancarlos** [comment]
Thank you so much, I hope it becomes a consideration in the future to avoid confusion. Also just to be clear is this GitHub repository the best way to receive announcements related to the Azure App Service?

My apologies if I should be asking these things elsewhere.

Thanks @davidebbo

**Comment by davidebbo** [comment]
This GitHub repo is a new thing we just started, but the intent is indeed to keep it updated with relevant announcements.
