### ISSUE TITLE
HTTP/2 protocol now available for App Service and Functions apps

### ISSUE THREAD

**Issue by odvoskin** [Azure/app-service-announcements#100]
See the official announcement here: https://blogs.msdn.microsoft.com/appserviceteam/2018/04/13/announcing-http2-support-in-azure-app-service/

Note support for App Service Environments and National clouds will shortly follow. Currently, the configuration is only available in the Resource Explorer but a UI option will be available soon.

**Comment by davidebbo** [comment]
Please use the comments at the bottom of the announcement post on MSDN if you have any questions about this change.
