### ISSUE TITLE
Deployment of ASP.NET 2.0.8 and .NET Core 2.1.0-rc1 to Azure App Service

### ISSUE THREAD

**Issue by watashiSHUN** [Azure/app-service-announcements#107]
@[.NET Core May 2018 Update](https://blogs.msdn.microsoft.com/dotnet/2018/05/08/net-core-may-2018-update/)
Please use https://github.com/Azure/app-service-announcements-discussions/issues/47 for discussions related to this deployment

**Comment by davidebbo** [comment]
The deployment is now complete.
