### ISSUE TITLE
Azure Functions Runtime 2.0 Preview Breaking Change Notice

### ISSUE THREAD

**Issue by fabiocav** [Azure/app-service-announcements#112]
### Azure Functions Runtime 2.0.11857 release

A new version of the Azure Functions Runtime 2.0, is being prepared.

This is notice is being posted in advance to prepare users running on the current Azure Functions 2.0 preview version for the following potential breaking changes: 

### **NodeJs Language Worker:** 
 - **Deprecating support for Node v6:** For JavaScript functions, please change WEBSITE_NODE_DEFAULT_VERSION in App Settings to _an 8.x version_ that is >=8.4.0.

### **Java Language Worker:** 

- Updates to Annotations package:
    - Updated package name for Azure Funcitons Annotations to **com.microsoft.azure.functions.annotation** to be consistent with rest of the azure functions libraries and SDKs.
    - Annotations with new package name is published to **azure-functions-library.jar**. Any further updates to annotations will only be published to this package.

#### To consume the latest functions runtime, following changes need to be made to existing java functions:

Changes needed to import statements in the function code:

Before

```
import com.microsoft.azure.serverless.functions.annotation.*;
import com.microsoft.azure.serverless.functions.*;
```
After (remove **serverless**):

```
import com.microsoft.azure.functions.annotation.*;
import com.microsoft.azure.functions.*;
```

Changes needed to pom.xml: **Update groupId, artificatId and version**
Before
```
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-functions-java-core</artifactId>
            <version>1.0.0-beta-2</version>
</dependency>
```
After
```
<dependency>
      <groupId>com.microsoft.azure.functions</groupId>
        <artifactId>azure-functions-java-library</artifactId>
        <version>1.0.0-beta-4</version>
</dependency>
```

New version of The Maven Tooling has been released:
- Maven Azure Functions plugin: `1.0.0-beta-2`
- Maven Azure Functions Archetype: `1.11`

Please note that it will take 2~3 days for Maven Central to update the newest version number. To use the latest Maven Azure Functions Archetype, explicitly specify the version in your command:

```
mvn archetype:generate -DarchetypeGroupId=com.microsoft.azure -DarchetypeArtifactId=azure-functions-archetype -DarchetypeVersion=1.11
```

### Other changes
 - **.NET default HTTP response JSON serialization:** The default serialization behavior was changed in 2.0.11776 (previous release) to pacal casing. This release will revert that change and return the behavior to use camel casing serialization.
 - **Visual Studio Tools:** .NET Core 2.1 will be required to run the updated Azure Functions Core tools

### What can I do to avoid being impacted?
 
To avoid impact, you can pin your Function App to the current version of the runtime now by updating the app setting `FUNCTIONS_EXTENSION_VERSION` to `2.0.11776-alpha`. Once the new version is released, you will not be automatically upgraded and will have the ability to test your code with the new version, which we recommend you do in a different Function App.
**This version will remain available until June 30th.**

Please use Azure/app-service-announcements-discussions#50 for discussions related to this release.

**Comment by mhoeger** [comment]
There was a breaking change for JavaScript functions I left out:

We are **deprecating support for Node v6**, which may affect deployed function apps. Please change WEBSITE_NODE_DEFAULT_VERSION in App Settings to an 8.x version that is >=8.4.0 (for example: 8.11.1).

**Comment by cgillum** [comment]
This runtime update also breaks the [Durable Functions extension](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-overview). If you are using Durable Functions on the v2 runtime, please set the `FUNCTIONS_EXTENSION_VERSION` app setting to `2.0.11776-alpha` to avoid being impacted. A new **1.5.0** release of the extension that is compatible with the latest Azure Functions runtime will be released soon. Please follow [this issue](https://github.com/Azure/azure-functions-durable-extension/issues/342) for additional updates.
