### ISSUE TITLE
Azure Functions Runtime 2.0.11888 Preview [breaking]

### ISSUE THREAD

**Issue by alrod** [Azure/app-service-announcements#117]
A new version of the Azure Functions Runtime Preview 2.0.11888 is being deployed.

Please refer to the latest release notes on the release page here for details:
https://github.com/Azure/azure-functions-host/releases/tag/v2.0.11888-alpha

This release has **breaking** changes:
- Temporarily, the 64-bit platform option is not supported. Previously when this option was selected it was ignored and the `w3wp.exe` process always started in 32-bit mode.  Please switch to 32-bit (x86) in "General Settings".  We are working to implement true 64-bit support in a future release.

**Known issues**:
 - `HttpTrigger ` does not return response content properly. For example following code will return "Bad Request" instead of "Please pass a name on the query string or in the request body":
`return new BadRequestObjectResult("Please pass a name on the query string or in the request body");`
If this is blocker you can use previous version by setting `FUNCTIONS_EXTENSION_VERSION=2.0.11857-alpha`.

Please use Azure/app-service-announcements-discussions#54 for discussions related to this release.

**Comment by davidebbo** [comment]
Update: you can now try this in the West Central US region.

**Comment by alrod** [comment]
This runtime deployment has been completed.

**Comment by davidebbo** [comment]
Keeping active till everyone gets through transition.
