### ISSUE TITLE
Azure Functions Runtime 2.0.11961 Preview

### ISSUE THREAD

**Issue by mhoeger** [Azure/app-service-announcements#128]
A new version of the Azure Functions Runtime 2.0.11961 is being deployed.

Please refer to the latest release notes on the release page here for details: https://github.com/Azure/azure-functions-host/releases/tag/v2.0.11961-alpha

Please use https://github.com/Azure/app-service-announcements-discussions/issues/63 for discussions related to this release.

**Comment by mhoeger** [comment]
@paulbatum - I'll let you take the question above about GA date :)

**Comment by jeffhollan** [comment]
Locking conversation for the discussion issue [linked above](https://github.com/Azure/app-service-announcements-discussions/issues/63) and responded there.
