### ISSUE TITLE
Microsoft.AspNetCore.App version 2.1.3 was not found

### ISSUE THREAD

**Issue by HaakonL** [Azure/app-service-announcements#130]
Hi,

when will this version be available in our App Service apps?

![image](https://user-images.githubusercontent.com/508432/44461744-51fda680-a612-11e8-896f-70eccf12e2e5.png)

**Comment by MaximRouiller** [comment]
https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.3/2.1.3.md#azure-appservices
**Last commit date:** Aug 21, 2018, 1:28 PM EDT

> Azure AppServices
Deployment of .NET Core 2.1.3 to Azure App Services will begin today and is expected to reach all regions by the end of the week.

**Comment by RobCubed** [comment]
Any update? I checked East/Central/South Central US App Service Plans and none of them have 2.1.3 installed.

**Comment by davidebbo** [comment]
Please do not open issues in this repo, or use it for discussions. It is only for announcements from the team, and can cause a lot of spam as many people are watching it. I have created a discussion thread for it: https://github.com/Azure/app-service-announcements-discussions/issues/65

**Comment by davidebbo** [comment]
https://github.com/Azure/app-service-announcements/issues/131
