### ISSUE TITLE
Set your V1 Function Apps to ~1

### ISSUE THREAD

**Issue by paulbatum** [Azure/app-service-announcements#135]
We have identified that a subset of customers have incorrectly configured V1 Function Apps. User action is required to configure these applications correctly to avoid potential impact.  In the coming days this will start redirecting to ~2 which will break the large majority of apps with this setting.

Function Apps use the FUNCTIONS_EXTENSION_VERSION app setting to control which version of functions the app runs on. A V1 Function App should have this setting set to ~1. It should look like this:

![image](https://user-images.githubusercontent.com/10663/45770079-4512a980-bbf6-11e8-8482-c830bb5a79bf.png)

and this:

![image](https://user-images.githubusercontent.com/10663/45769934-ecdba780-bbf5-11e8-8e31-dfa5baf626af.png)

## Take Action

If you have a V1 app and you don't have this setting, fix it. Make sure it is set to ~1. Don't use values such as "latest" or "" (i.e. empty string). 

If you have an automated deployment of any kind, make sure that your automated deployment is setting this correctly. We've seen cases where ARM templates are being executed that are missing this setting.

Also if you have a V2 app, you should set it to ~2 instead of "beta". That will prevent your V2 app from running into similar issues in the future.

## Questions?

Please use https://github.com/Azure/app-service-announcements-discussions/issues/69 for discussion of this announcement.

**Comment by davidebbo** [comment]
Note that this is a continuation of this announcement from August 2017: https://github.com/Azure/app-service-announcements/issues/34. So this one is a reminder, as we're now about to release 2.0.
