### ISSUE TITLE
New app_offline.htm behavior for Kudu publishing workflows

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements#137]
In an effort to make Kudu deployments avoid file locking issues, Kudu will now create a temporary app_offline.htm in the site's wwwroot folder before starting the deployment. Kudu then takes care of deleting the file after deployment is complete.

The effect is that while deployment is happening, the app will be kept offline. In addition to avoiding file locking issues, this helps keep the site is a consistent state, by not serving any traffic while the contents of the site is only half-deployed.

Note: the file will only be created if an app_offline.htm file is not already present in the site's folder. 

If you'd like to turn this behavior off, please add an `SCM_CREATE_APP_OFFLINE` App Setting to your app and set the value to 0. For more information about configurable settings, please check [this page](https://github.com/projectkudu/kudu/wiki/Configurable-settings).

Note that this is the same mechanism that msdeploy has supported for a long time.

**Comment by davoodharun** [comment]
should this be assumed to be the default behavior from this point forward?

**Comment by davidebbo** [comment]
@davoodharun yes.

Closing since this is fully deployed for a while now.

**Comment by codecadwallader** [comment]
@davidebbo We've been having a lot of issues recently with the app_offline.htm file being left behind after Kudu finishes.  Combined with our app service auto-swapping into production, this is causing a production outage.  I'm not sure which repo is the correct repo to report this issue, do you have a recommendation?  Also of course any help with the actual issue would be greatly appreciated.  Thanks!

**Comment by kjohann** [comment]
Same thing happens to us. After deploy, the app_offline.htm-file is still there, causing the app to give a 503 with a title of "Site under construction". Deleting the file from KUDU resolves the issue. We thought this was a random issue in our test environments for a while, but just now we started seeing this in production as well. The deployment process is similiar in all environments - the only difference is the service plan. Our apps are running in an App Service Environment - have not experienced this issue on standard App Service Plans yet.

**Comment by niklaslundberg** [comment]
I'm experiencing the same bahavior in standard AppServices deployed with WebDeploy.

**Comment by davidebbo** [comment]
@codecadwallader @kjohann @niklaslundberg I'm not longer working on Kudu. @ahmelsayed should be able to comment on whether something changed recently that could affect this. You might also want to open an issue on the Kudu repo.

**Comment by codecadwallader** [comment]
Thanks @davidebbo I've created https://github.com/projectkudu/kudu/issues/2949

**Comment by shmulyeng** [comment]
Is there a way to customize the app_offline.htm file used?
