### ISSUE TITLE
App Service (Windows) Sites running Python 3.4.1 will be updated to Python 3.6.6 starting November 12th

### ISSUE THREAD

**Issue by stefsch** [Azure/app-service-announcements#144]
Starting on Monday November 12th, and running through December 15th, Azure App Service (Windows) will be upgrading all Python sites running Python 3.4.1 to instead run Python 3.6.6 to address security vulnerabilities in Python 3.4.1.  

The upgrade is an “in place” update, and will automatically update the Python binaries currently used by Python 3.4.1 applications.  We recommend customers test existing Python 3.4.1 sites with Python 3.6.6, and make any necessary code changes to ensure their web sites are compatible with the newer Python version.  

However, if it is not possible to modify a site’s code to make it compatible with Python 3.6.6, customers can instead manually configure a site to use Python 3.4 using the following procedure:

1. Install python 3.4 by downloading it from:  https://www.python.org/downloads/release/python-340/ and install it on your local machine.  For purposes of this example the installation will be made to c:\Python34

2. In your local development environment, create a sub-directory inside of your website’s directory structure to hold a copy of the older Python 3.4 binaries.  For purposes of this example, create a sub-directory called Python34 under wwwroot.

3. Copy the Python 3.4 binaries from your local development environment into wwwroot\Python34.

4. Edit the web.config file in wwwroot ensuring the <handlers> configuration section is configured as shown below:

```
<system.webServer>
     <handlers>
          <remove name="Python34_via_FastCGI"/>
          <add name="Python34_via_FastCGI" path="*" verb="*" modules="FastCgiModule" scriptProcessor="d:\home\site\wwwroot\Python34\Python.exe|%SystemDrive%\Python34\Scripts\wfastcgi.py" resourceType="Either" />
     </handlers>
</system.webServer>

```

5. Create a file on in your local development environment called applicationHost.xdt

6. Add the following configuration snippet to applicationHost.xdt:

```
<?xml version="1.0"?>
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <system.webServer>
    <fastCgi>
      <application fullPath="d:\home\site\wwwroot\Python34\python.exe" xdt:Locator="Match(fullPath)" xdt:Transform="Remove" />
      <application fullPath="d:\home\site\wwwroot\Python34\python.exe" arguments="D:\Python34\Scripts\wfastcgi.py"  maxInstances="0" xdt:Transform="Insert"/>
    </fastCgi>
  </system.webServer>
</configuration>
```

7. Redeploy the web app from your local development environment to Azure App Service.

8. Deploy the applicationHost.xdt that was created earlier into the d:\home\site\ directory of the website running on Azure App Service.

9. After deploying both the updated application, and the applicationHost.xdt file, restart the website for the changes to take effect.

Regards, 
The Microsoft Azure Team

**Comment by fashaikh** [comment]
For those facing issues: 
`copy the python34.dll from you c:\windows\system32 folder  over the \Python34\ folder in your app service`

![image](https://user-images.githubusercontent.com/2650941/50315151-6d64ab00-0466-11e9-9a63-00219fdbcaf0.png)
