### ISSUE TITLE
.NET Core 2.2 availability on App Service

### ISSUE THREAD

**Issue by stefsch** [Azure/app-service-announcements#151]
.NET Core 2.2 is now available in all regions for **public** App Service (Windows).
.NET Core 2.2 is also now available for all App Service Environments running in **public** App Service.
.NET Core 2.2 is also now available for all sovereign cloud regions.
.NET Core 2.2 is also now available in all regions for the Linux variation of App Service.

More details on .NET Core 2.2 features here:  
[https://blogs.msdn.microsoft.com/dotnet/2018/12/04/announcing-net-core-2-2/]

Discussion issue: https://github.com/Azure/app-service-announcements-discussions/issues/87

**Comment by Leon99** [comment]
Any timeframes for 2.2.2? There was a critical fix made in it (https://github.com/aspnet/AspNetCore/issues/6543).
