### ISSUE TITLE
In-portal editing will be disabled for Python Functions

### ISSUE THREAD

**Issue by asavaritayal** [Azure/app-service-announcements#157]
Currently, Python Function Apps on Functions v2, deployed to a Linux App Service Plan allow in-portal file editing. This feature will be disabled starting March 2019. 

For a comprehensive development and debugging experience, please use the [Azure Functions Core Tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-first-function-python) or [VS Code extension](https://code.visualstudio.com/tutorials/functions-extension/getting-started). 

[Use this issue for discussion](https://github.com/Azure/app-service-announcements-discussions/issues/88)

**Comment by laurentbastien** [comment]
How do you deploy python code to a Windows machine without in-portal file editing? Currently, publishing Python functions with the CLI is only supported on Linux.

**Comment by sfkleach** [comment]
I would assume Local Git Repo deployment would work - it's what I use for Azure Functions. If you are even older school then maybe OneDrive sync?

**Comment by TecumsehSamp** [comment]
Surely all Python Functions run on Linux in Azure now?

Or am I missing something (I know people could run it before on Windows hosts)?

**Comment by zooba** [comment]
Publishing from Windows should work fine, even though the code will eventually run on Linux.

The [instructions here](https://docs.microsoft.com/azure/azure-functions/functions-reference-python#publishing-to-azure) are only shown for Bash, but will work fine on Windows as well. You'll need all the dependencies as well though (Node.js, Docker, etc.)

Alternatively, further down that page it shows how to set up Azure Pipelines to do the deployment for you. The free tier of Azure Pipelines will have more than enough build time (and I personally think it's easier to set up than Docker ;) ).

**Comment by jeffhollan** [comment]
Updating this issue as this does include disabling the template creation of experimental Python from the portal.  We do not recommend any users create new experimental v1 Python apps as they are not supported and have many limitations that were solved in the v2 preview of Python.

[Feel free to use this issue for discussion](https://github.com/Azure/app-service-announcements-discussions/issues/88)

Thanks
