### ISSUE TITLE
Node v4.8.4, v6.11.1, v7.10.1 and v8.1.4 now available

### ISSUE THREAD

**Issue by suwatch** [Azure/app-service-announcements#19]
New Nodejs versions along with relavant NPMs are now available on Azure AppServices to address [the vulnerability](https://nodejs.org/en/blog/vulnerability/july-2017-security-releases/).

**Comment by yvele** [comment]
Related to https://github.com/Azure/azure-webjobs-sdk-script/issues/1682#issuecomment-316757655
