### ISSUE TITLE
.NET 4.7 for Azure App Service

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements#2]
[Originally on [MSDN forum](https://social.msdn.microsoft.com/Forums/azure/en-US/b396db29-224f-4a11-a952-14d31666e342/net-47-for-azure-app-service?forum=windowsazurewebsitespreview)]

Azure App Service will get support for .NET 4.7 by the end of June 2017. Please refer to [this announcement](https://blogs.msdn.microsoft.com/dotnet/2017/04/05/announcing-the-net-framework-4-7/) for more .NET 4.7 specific information.

**Comment by davidebbo** [comment]
The release has started, and is still on track to complete by end of June.

**Comment by aaronengtech** [comment]
The .Net 4.7 update broke our Sitefinity based website hosted on the Azure app service.  We didn't know this update was rolled out until we used the Kudu console and viewed the registry on the box to find out.  This was a difficult issue to track down and cost us downtime (the azure portal gives no indication this changed).  This post is the only information I could find related to the Azure app service release of .Net 4.7.  :weary: :sweat:

**Comment by davidebbo** [comment]
@aaronengtech It was also announced on our [MSDN forum](https://social.msdn.microsoft.com/Forums/azure/en-US/b396db29-224f-4a11-a952-14d31666e342/net-47-for-azure-app-service?forum=windowsazurewebsitespreview).

But the fact that it breaks SiteAffinity was of course not expected, and seems to come down to some ASP.NET regression.

It looks like SiteAffinity released a [patch](http://knowledgebase.progress.com/articles/Article/local-site-suddenly-stopped-working-after-running-the-windows-10-updates) for it.

**Comment by aaronengtech** [comment]
We were able to get things patched and working again.  Is there an easier way from the Azure portal to see that this update has happened or do we have to use the kudu console (req query) to find out for sure?

**Comment by davidebbo** [comment]
In term of announcements, it's best to follow this issue tracker, where we try to announce anything that may be relevant.

In term of knowing if a particular instance has been updated while we are in the transitional deployment stage (as we are right now), there is no great way to know form the portal. Note that we're just a few days from completing this deployment, at which point you can assume that 4.7 is everywhere.

**Comment by SimonLuckenuik** [comment]
Is it possible that this update somehow broke IIS AspNetCore Module / dotnet core integration with IIS? Out of nowhere, yesterday we started to have issues with our application which has been deployed for a while now and was working correctly. Sample of our IIS eventlog.xml below. After sometime, the AspNetCore Module is then able to start again the dotnet process.
<Event>
<System>
<Provider Name="IIS AspNetCore Module"/>
<EventID>1000</EventID>
<Level>0</Level>
<Task>0</Task>
<Keywords>Keywords</Keywords>
<TimeCreated SystemTime="2017-06-28T12:44:15Z"/>
<EventRecordID>60350640</EventRecordID>
<Channel>Application</Channel>
<Computer>RD0003FF812E87</Computer>
<Security/>
</System>
<EventData>
<Data>
Application 'MACHINE/WEBROOT/APPHOST/<REMOVED>' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline 'dotnet .\WebService.dll', ErrorCode = '0x80004005 : e0434352.
</Data>
</EventData>
</Event>

<Event>
<System>
<Provider Name="IIS AspNetCore Module"/>
<EventID>1001</EventID>
<Level>0</Level>
<Task>0</Task>
<Keywords>Keywords</Keywords>
<TimeCreated SystemTime="2017-06-28T12:45:52Z"/>
<EventRecordID>60447593</EventRecordID>
<Channel>Application</Channel>
<Computer>RD0003FF812E87</Computer>
<Security/>
</System>
<EventData>
<Data>
Application 'MACHINE/WEBROOT/APPHOST/<REMOVED>' started process '584' successfully and is listening on port '15241'.
</Data>
</EventData>
</Event>

**Comment by davidebbo** [comment]
@SimonLuckenuik very unlikely, as .NET Core apps don't use the full .NET fx at all. Please start a separate thread on the [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview). Thanks!

**Comment by MichalGrzegorzak** [comment]
Sorry need some clarification here. When you finish the deployment, would I be able to see in Portal, new .NET 4.7 version to choose from? Or this is 'invisible' upgrade - behind the scenes, and user has nothing to decide?

**Comment by davidebbo** [comment]
@MichalGrzegorzak It is the latter, as .NET Framework updates are always in-place and not side by side. Even though the portal has not yet been updated to say 4.7, almost every site by now is already running it, and that is the only 4.x version available. So don't rely on the portal to know if the upgrade has reached your site.

**Comment by MaximRouiller** [comment]
@davidebbo Is it possible to do like ASP.NET and lock threads when an issue is created and post discussions in a separate repository?

That way, I can *Watch* this repo and not get spammed when a discussion I'm not interested in starts?

This one is interesting mind you but I can't say for all future conversations. :wink:

**Comment by davidebbo** [comment]
@MaximRouiller yes, we will look into that. They probably have some automation that creates the matching discussion discussion thread. We'll talk to them. Thanks!

**Comment by davidebbo** [comment]
Please use https://github.com/Azure/app-service-announcements-discussions/issues/1 for further discussion.

**Comment by davidebbo** [comment]
The 4.7 upgrade is complete.
