### ISSUE TITLE
Cannot upload/create/delete files when customer connects to the FTPS endpoint from deployment center

### ISSUE THREAD

**Issue by MSShashankRanjan** [Azure/app-service-announcements#210]
When we go to the deployment center and copy the FTPS endpoint, we are able to login to FTP. However, we cannot upload/create/delete files.

We could see that endpoint URL has "dr" appended. After removing the "dr", it works.

This is the mitigation but needs the fix for the issue.

I am raising the issue on behalf of customers who raised support ticket.

**Comment by earnsah** [comment]
Any updates on this issue? Do we have a turnaround time for this fix to get released?

**Comment by ahmelsayed** [comment]
Please don't use this repo to repot issues. Check the README on how to do that.
