### ISSUE TITLE
64-bit versions of the node.exe

### ISSUE THREAD

**Issue by jsheely** [Azure/app-service-announcements#22]
Can we please, I'm begging, get a 64-bit version of the node.exe available in the Azure web app base?

I know I can bring my own node.exe. Except that when I use my own I can't replace it while the application is in use (git repo pushes). Not to mention issues with the path to that executable depending on environments. 

You're already providing the 32-bit version. Is there any particular reason the 64-bit versions aren't copied as well?

**Comment by davidebbo** [comment]
This repo is only used for announcements y the team. Please use https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview or https://feedback.azure.com/forums/169385-web-sites/ instead,
