### ISSUE TITLE
Platform upgrade for Azure Functions v2 apps coming in October 2020

### ISSUE THREAD

**Issue by anthonychu** [Azure/app-service-announcements#266]
> If you received a notification email recently but have already made the change to your app, do note that we sent mails to all apps over the last 30-40 days. If you made the change after that time you can safely ignore

UPDATE (Oct 5 2020): To prevent existing applications from being impacted, we will begin the process of automatically opting out apps that are still at risk for breaking that have not either upgraded to v3 or opted out already.  We will opt the apps out by changing the `FUNCTIONS_EXTENSION_VERSION` to `~2.0`.  It is worth noting by redeploying from something like an ARM template users may inadvertently opt back in if they change that setting.

---

On October 31, 2020, we will begin a platform upgrade for Azure Functions v2 apps that may impact your app.  This upgrade will enable us to continue providing security patches at all layers of the application moving forward.  The large majority of users will be unimpacted and don’t need to take any action, but a small set of apps may be using APIs in their code that will break as a result of this upgrade.

For apps that are written in Java, JavaScript, Python, and PowerShell<sup>1</sup>, there will be no impact on your application.

For the majority of applications in .NET, there will be no impact on your application.  However, if you have a .NET Azure Functions v2 app with application code that leverages a [.NET API that was deprecated or changed in .NET 3.1](https://docs.microsoft.com/en-us/dotnet/core/compatibility/2.2-3.1), your app will be impacted.  You will need to choose to opt-out of the platform upgrade, meaning some aspects of the underlying runtime may no longer receive certain security patches after October 2020, or modify your application to be .NET Core 3.1 compatible.

We will be sending notices to subscriptions for applications that are using .NET APIs that are at risk for breaking with this platform upgrade.  

If you wish to opt-out of this platform upgrade, you can do so and no changes to your application code would be required.  This does mean future host releases and security patches would not be applied to these applications. 

Information on how to upgrade your impacted applications or opt-out can be found here:
https://github.com/Azure/azure-functions-host/wiki/Platform-upgrade-from-Azure-Functions-runtime-v2-to-v3

If you have any questions, please use the following GitHub discussion: 
https://github.com/Azure/app-service-announcements-discussions/issues/175

<sup>1</sup> *If your PowerShell function is calling .NET libraries that are not .NET Core 3.1 compatible, it may be impacted.*

**Comment by jeffhollan** [comment]
Heads up if you want to leave a comment or have a question discussion is happening in this issue:
Azure/app-service-announcements-discussions#175

**Comment by pragnagopa** [comment]
We will start platform upgrade process on 11/9/2020. Please note that upgrade process will span over multiple weeks. Please post any questions/issues on the discussion issue Azure/app-service-announcements-discussions#175

**Comment by pragnagopa** [comment]
Update on 12/8 : Auto-upgrade completed for consumption plan function apps running on Linux. Upgrade for the rest of the hosting plans is in progress.

**Comment by pragnagopa** [comment]
Update on 12/10 : Auto-upgrade completed for function apps running on Linux in Public Azure.

**Comment by pragnagopa** [comment]
Update on 12/16: We have paused the upgrade process on windows as few of the apps ran into blocking issue https://github.com/Azure/azure-functions/issues/1370 .  We will resume upgrade process in January. Please see discussion issue https://github.com/Azure/app-service-announcements-discussions/issues/175 for more details.

**Comment by pragnagopa** [comment]
Update 01/05 :
1. We have prepared fix for apps that have dependency on `System.Data.SqlClient` . We will resume Auto-Upgrade 
2. We have identified an issue in the platform with x64 consumption function apps running on windows https://github.com/Azure/azure-functions-host/issues/6999 . Fix will be rolled out by end of this month. Until then, we will be actively pinning these apps to Functions V2 by updating App Setting FUNCTIONS_EXTENSION_VERSION to ~2.0

**Comment by pragnagopa** [comment]
Update 01/14/21:

Auto-Upgrade for Function Apps running on Windows completed in regions: West Central US, West US2, West Europe

Upgrade will be rolled out to rest of the regions in the next few days.

**Comment by pragnagopa** [comment]
Update 01/15/21:
Deployment will be completed today for all the regions.

**Comment by pragnagopa** [comment]
Update 01/17/21:
Deployment to all regions completed on 01/15/21. Please post any follow up questions on discussion issue Azure/app-service-announcements-discussions#175

**Comment by pragnagopa** [comment]
Auto-Upgrade roll out is completed in all the regions. Closing this issue.
