### ISSUE TITLE
"Try Functions" not working . Use https://functions-next.azure.com/try as a workaround

### ISSUE THREAD

**Issue by fashaikh** [Azure/app-service-announcements#29]
We are tracking an issue with the Try Functions UI (https://github.com/Azure/azure-functions-ux/issues/1682) . 

As a workaround feel free to use https://functions-next.azure.com/try till the fix is propagated to production.

**Comment by fashaikh** [comment]
Fix has been deployed. Please use https://functions.azure.com/try going forward

**Comment by jkkoolen** [comment]
https://functions.azure.com/try does not work. Get an empty page
