### ISSUE TITLE
New Release of Durable Functions: 0.2.2-alpha

### ISSUE THREAD

**Issue by cgillum** [Azure/app-service-announcements#30]
This release includes a variety of changes and fixes, including some minor breaking changes. Most importantly, the Visual Studio setup experience has been significantly improved due in part to several changes included in the final release of [Visual Studio 2017 (15.3)](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes).

The VS sample project has also been updated to highlight these major changes:

* Durable Functions can be added to any Azure Functions project via [a simple NuGet package reference](https://azure.github.io/azure-functions-durable-extension/articles/installation.html).
* Activity functions can now [bind to any JSON-serializeable data type](https://azure.github.io/azure-functions-durable-extension/articles/topics/bindings.html#trigger-sample-1), including primitive types.

Security has also been improved by taking advantage of the new [System Keys feature of Azure Functions](https://github.com/Azure/azure-webjobs-sdk-script/pull/1659).

More technical details can be found in the following PR:
[Updates for 0.2.2-alpha: Activity binding, System Keys, & improved Visual Studio support](https://github.com/Azure/azure-functions-durable-extension/pull/18)

For an overview and detailed documentation of Durable Functions, see our GitHub Docs page: https://azure.github.io/azure-functions-durable-extension/

**Comment by davidebbo** [comment]
Please use https://github.com/Azure/azure-functions-durable-extension/issues is you have any questions/issues about this announcement or durable functions in general. Thanks!
