### ISSUE TITLE
Functions users: make sure you are not negatively affected by 2.0 release

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements#34]
In the not so distant future (no ETA yet), we will release version 2.0 of the Functions runtime. Normally, Function Apps have their `FUNCTIONS_EXTENSION_VERSION` app setting set to `~1`, which means they will continue to run 1.x after 2.x is released. This is a good things since 2.x will have some breaking changes.

However, a small percentage of apps don't have `FUNCTIONS_EXTENSION_VERSION` set at all, or have it set to `latest`. These, will automatically move up to the 2.x runtime once it is released. **If you are in this situation, make sure that it is the behavior that you want. If not, please change the app setting to `~1`**.

Please use https://github.com/Azure/app-service-announcements-discussions/issues/11 is you have any questions.

**Comment by davidebbo** [comment]
We'll have some more details about a 2.0 Preview soon. Here are some key high level changes:

- It runs on .NET Core instead of full fx. That makes it cross platform.
- It runs Node out of proc instead of relying on Edge.JS

**Comment by paulbatum** [comment]
The 2.0 preview has been live for 6+ months. Closing this.
