### ISSUE TITLE
[Azure Functions] [V4] Application Insights is now available as an extension (breaking change)

### ISSUE THREAD

**Issue by anthonychu** [Azure/app-service-announcements#346]
As of Azure Functions host version 4.0.0.16394, Application Insights is no longer included by default. It is now available as a separate extension.

For more information on the background behind this change, see [this issue](https://github.com/Azure/Azure-Functions/issues/2027).

## Impact

In Azure Functions 4.0.0.16394, Application Insights will not work until it is added as an extension (instructions below).

In future versions of Azure Functions 4.x, the host will not start if `APPINSIGHTS_INSTRUMENTATIONKEY` or `APPLICATIONINSIGHTS_CONNECTION_STRING` have been set but the extension is not installed.

## Enable Application Insights extension

The steps to enable the Application Insights extension depends on the type of app.

### .NET

For **in-process** .NET apps, install version 1.0.0-preview4 or later of the [Microsoft.Azure.WebJobs.Extensions.ApplicationInsights](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ApplicationInsights/) extension package. Also, make sure that the [Microsoft.NET.Sdk.Functions](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/4.0.0-preview2) package referenced by the function app is version 4.0.0-preview2 or newer.

For **isolated** .NET apps, install version 1.0.0-preview4 or later of the [Microsoft.Azure.Functions.Worker.Extensions.ApplicationInsights](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.ApplicationInsights/) extension package. Also, make sure that the [Microsoft.Azure.Functions.Worker](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker/) and [Microsoft.Azure.Functions.Worker.Sdk](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/) are updated to the latest versions.

### Other languages

For other languages, a future update to [Azure Functions extension bundles](functions-bindings-register.md#extension-bundles) will include the Application Insights extension. Your app will automatically use the new bundle when it is available.

## Discussions

Please post any questions in the discussion issue - https://github.com/Azure/app-service-announcements-discussions/issues/248

**Comment by liliankasem** [comment]
It might be worth mentioning you need to be on [v4 of the Sdk](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/4.0.0-preview2) for this to work, as noted in this issue:

https://github.com/Azure/azure-functions-host/issues/7724

**Comment by gzuber** [comment]
This breaking change has been abandoned and is not included in the Functions V4 release. We're re-evaluating the Application Insights Extension, but for now the default integration/behavior remains unchanged.
