### ISSUE TITLE
Updating PHP to latest versions

### ISSUE THREAD

**Issue by odvoskin** [Azure/app-service-announcements#36]
In the next release of Azure Web Apps, we will update the PHP stacks to the latest available versions.
For information on the changes in the new versions, please see the change logs on the PHP website.

PHP Version | Change log
-- | --
7.0.23 | http://www.php.net/ChangeLog-7.php#7.0.23
7.1.8 | http://www.php.net/ChangeLog-7.php#7.1.8

**Comment by EricSten-MSFT** [comment]
FYI, The release of Azure Web Apps containing the PHP stacks listed above has completed.
