### ISSUE TITLE
Proxies (preview) Breaking Change

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/app-service-announcements#50]
In the most recent version of the Functions runtime (1.0.11296.0) we have introduced a few breaking changes in regards to how Functions Proxies behave. 

|Issue|Description|Status|
|---|---|---|
|Proxy names must now follow function naming requirements|https://github.com/Azure/azure-functions-ux/issues/1878 Any Proxies named with invalid characters will now return 500|**Fixed**|
|A proxy that matches all incoming routes will block all requests to a function|A proxy with a catchall route **/{\*var}** and a backend URI pointing at the same function app will result in an infinite loop and 400 response. That proxy will also intercept all traffic to all HTTP triggered functions and return 400|**Fixed** https://github.com/Azure/azure-webjobs-sdk-script/pull/2060|
|All Proxies return 404| If the application setting ROUTING_EXTENSION_VERSION is ~0.2 all Proxies will return 404|**Fixed**|
|Proxies No longer accept "?" in routes| https://github.com/Azure/azure-webjobs-sdk-script/issues/1993 Proxies that include hardcoded query strings in the route no longer work. Example "/add?a={var}"|[Will not fix](https://github.com/Azure/azure-webjobs-sdk-script/issues/1993)|

**Comment by davidebbo** [comment]
Please use https://github.com/Azure/app-service-announcements-discussions/issues/16 for discussions about this change.
