### ISSUE TITLE
Azure Functions Proxies not Supported in Functions 2.0

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/app-service-announcements#68]
We do not have Functions Proxies support in the 2.0 (beta) runtime of Functions. We are working hard to get Proxies running, and expect to have support in early January.

We will not be changing the proxies.json schema in the move from 1.0 to 2.0. It will be trivial to copy any Proxies from 1.0 to 2.0

To use Proxies with a 2.0 Function, you will need to host them in a separate Function running the 1.0 runtime.

The discussion on this feature is here https://github.com/Azure/azure-webjobs-sdk-script/issues/2055

**Comment by alexkarcher-msft** [comment]
Added this issue to the list of 2.0 known issues
https://github.com/Azure/azure-webjobs-sdk-script/wiki/Azure-Functions-runtime-2.0-known-issues

**Comment by fabiocav** [comment]
Proxies support has been reintroduced with 2.0.11776.
