### ISSUE TITLE
Azure Functions: fixes coming to enforcement of max execution time

### ISSUE THREAD

**Issue by paulbatum** [Azure/app-service-announcements#73]
Function Apps in the consumption plan have a default maximum execution time of 5 minutes (this can be increased to 10 minutes through config, but no further - for more info see [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale)). However a regression was introduced a few months ago that prevented this enforcement from occurring for functions authored and built in Visual Studio. 

We are now in the process of rolling out a fix for this regression. If you have functions that are running longer than the configured timeout, you'll start seeing the following message in your logs: `Timeout value of 00:05:00 was exceeded by function: Functions.<functionname>`. This is expected and we recommend you try to break your functions up into several function executions of shorter length.

**Comment by davidebbo** [comment]
The fix is deployed.
