### ISSUE TITLE
The type or namespace name 'ConnectionStringSetting' could not be found

### ISSUE THREAD

**Issue by ekzarov** [Azure/app-service-announcements#77]
After I have added CosmosDb trigger function I received the following error:
Error	CS0246	The type or namespace name 'ConnectionStringSetting' could not be found (are you missing a using directive or an assembly reference?)	MyTest.Functions.Data	C:\TestPath\Function1.cs

https://prnt.sc/i5jar5

**Comment by davidebbo** [comment]
This tracker is only of announcements. Please use [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=AzureFunctions) or StackOverflow for questions. Thanks!
