### ISSUE TITLE
Avoid enabling 'HTTPS only' for applications with 'Always On' enabled

### ISSUE THREAD

**Issue by paulbatum** [Azure/app-service-announcements#78]
We've discovered that the recently introduced "HTTPS Only" feature (documented [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-custom-ssl#enforce-https)) prevents "Always On" (documented [here](https://docs.microsoft.com/en-us/azure/app-service/web-sites-configure)) from working correctly. 

This is especially relevant for function apps on a dedicated app service plan, as many of these applications receive no HTTP traffic and rely on Always On to make sure the application stays active and processing events. If you've recently encountered an issue when your function app is not processing events when expected, this might be the root cause. Please note that function apps on the consumption plan do not use Always On and aren't impacted by this issue.

We're working on a fix for this issue - current ETA is mid February. In the meantime, we recommend you do not enable HTTPS Only if you want Always On to work correctly, especially for function apps as mentioned above.

Accessing the setting from the functions UX in the Azure portal is reasonably straightforward - go to Platform Features -> Custom Domains and then turn the setting off:
![image](https://user-images.githubusercontent.com/10663/35420122-97e0dbac-01f0-11e8-89be-2919a35a16b7.png)
![image](https://user-images.githubusercontent.com/10663/35420141-b0df610a-01f0-11e8-805f-136efcd388a9.png)

We'll update this issue once the fix has been deployed.

**Comment by davidebbo** [comment]
Please use https://github.com/Azure/app-service-announcements-discussions/issues/28 for discussions.

**Comment by paulbatum** [comment]
Deployment of the fix is complete. It is now safe to enable the HTTPS only setting. Please comment in https://github.com/Azure/app-service-announcements-discussions/issues/28 if you notice any problems (and @ me so I can follow up).
