### ISSUE TITLE
`az webapp new` now supports .NET Core apps

### ISSUE THREAD

**Issue by ahmedelnably** [Azure/app-service-announcements#85]
Check the blog post for more information
[aka.ms/new-cli](http://aka.ms/new-cli)

**Comment by darshanrampatel** [comment]
@ahmedelnably your link currently points to `https://github.com/Azure/app-service-announcements/issues/url` not `aka.ms/new-cli`

**Comment by davidebbo** [comment]
@darshanrampatel fixed, thanks!
