### ISSUE TITLE
App Service upgrade to .NET Framework 4.7.2

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements#89]
### **Update 9/27/2018: this was initially going to start in September, but the start date has now changed to mid October, and will complete in early November.**

Starting in mid October 2018, .NET Framework 4.7.2 will be available on App Service (which currently runs 4.7.1). We do not expect any foreseeable disruptions caused by this update, and have a high level of confidence in its backwards compatibility.

See https://blogs.msdn.microsoft.com/dotnet/2018/04/30/announcing-the-net-framework-4-7-2/  for more details about this release.

For a higher level of confidence in your app, you are encourage to verify on your own machines that your app runs fine on 4.7.2. 

## Instructions to test your app locally

1. Ensure you have [.NET Framework 4.7.2](http://go.microsoft.com/fwlink/?linkid=863262) installed on the local test machine
2. Deploy your App Service app (Web app, Function, API App or mobile app) on the local machine by hitting F5 in your Visual Studio project
3. Open the browser, hit the local site URI, and test functionality

### Can I prevent my app from being upgraded

All VMs will be moved to the new framework, so all apps will be upgraded. It will not be possible to move back. This is in line with every .NET framework upgrade that has happened in the past.

### Can I know exactly what day my app will be upgraded

This cannot easily be predicted, as the upgrade will happen progressively through October.

### How can I tell what the current .NET Framework version is in my App

Based on [this page](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed). From Kudu console, run:
    reg query "HKLM\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full" /v Release
- `0x709fe` (461,310) -> .NET 4.7.1
- `0x70bf6` (461,814) -> .NET 4.7.2

**Comment by davidebbo** [comment]
Please use https://github.com/Azure/app-service-announcements-discussions/issues/37 if you have any questions or run into any issues.

**Comment by davidebbo** [comment]
Re-opening as the update is not yet complete.

**Comment by fabiocav** [comment]
This deployment has been completed.
