### ISSUE TITLE
Preview of improved Functions http scaling behavior

### ISSUE THREAD

**Issue by davidebbo** [Azure/app-service-announcements#90]
We have made improvements to the http scaling, which greatly improves those scenarios. At this point, a Preview of the behavior can be tried by setting an App Setting on your app: `WEBSITE_HTTPSCALEV2_ENABLED=1`.

Notes:

- Despite the flag having 'v2' in its name, this works with either the v1 or v2 runtime
- The flag is temporary. When the changes are fully released, they will be on by default for everyone
- There will also be further improvements when it is released. But the flag as it exists today already gives nice improvements over the current scaling.

**Comment by davidebbo** [comment]
Please use https://github.com/Azure/app-service-announcements-discussions/issues/38 to discuss.

**Comment by paulbatum** [comment]
These changes were fully released a few months ago. Closing.
