### ISSUE TITLE
PHP Minor Version Update for May 2018

### ISSUE THREAD

**Issue by Jen7714** [Azure/app-service-announcements#98]
Latest version updates to PHP

In May 2018, Azure App Service will update the PHP stacks to the latest available versions (including MSSQL Drivers for PHP 7.2). For information on the changes in the new versions, please see the change logs on the PHP website.

PHP Version | Change Log
-- | --
5.6.35 | http://www.php.net/ChangeLog-5.php#5.6.35
7.0.29 | http://www.php.net/ChangeLog-7.php#7.0.29
7.1.16 | http://www.php.net/ChangeLog-7.php#7.1.16
7.2.4 | http://www.php.net/ChangeLog-7.php#7.2.4

**Comment by EricSten-MSFT** [comment]
Please use https://github.com/Azure/app-service-announcements-discussions/issues/43 for all discussion on this issue.
